"""Generate the compiled extension catalog from the supplied CSV plus macOS defaults.
No file content is inspected at runtime. Run from any directory with Python 3.
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'Reference/df_file_extensions.csv'
DESTINATION = ROOT / 'Orderly/Intelligence/ExtensionCatalog.swift'

GROUPS = {
    'document': 'pdf doc docx docm dot dotx txt text asc page pages rtf rtfd odt ott wpd wps xls xlsx xlsm xlt xltx numbers ods csv tsv ppt pptx pptm pot potx key keynote odp epub mobi azw azw3 djvu md markdown rst tex latex bib ps eps eml msg ofx qif ged egt mht mhtml',
    'image': 'jpg jpeg jpe png gif heic heif webp tiff tif bmp dib ico icns svg svgz avif apng dng cr2 cr3 nef arw orf rw2 raf raw psd psb ai sketch procreate afphoto afdesign dcm dicom fits fit fts iff ilbm lbm brik head mgh mgz gii nii',
    'application': 'deb rpm snap flatpak flatpakref appinstaller msu ipsw dmg pkg mpkg msi msp msix msixbundle appx appxbundle exe apk apks aab ipa xap xpi vbox-extpack cia',
    'code': 'swift python py pyw pyi ipynb js jsx mjs cjs ts tsx html htm xhtml xht css scss sass less json jsonc jsonld xml yaml yml toml ini plist sh bash zsh fish c cc cpp cxx h hh hpp m mm metal rs go java kt kts class jar war ear a o so dylib framework xcframework rb php php3 php4 php5 php7 php8 phtml pl pm r R jl lua sql dart vue svelte lock conf cfg cnf adp asp aspx bml cfm cgi ihtml jsp kprx las lasso lassoapp se shtml stm tpl xslt xsl yni ko nlm ocx tlb vap vbx',
    'artifact': 'ds_store tmp temp log swp swo part partial crdownload opdownload !ut',
    'archive': 'zip zipx rar 7z tar gz gzip tgz bz bz2 tbz tbz2 xz txz lz lzma lz4 z zst zstd sit sitx sea cab xar cpio ar aa aar nii.gz tar.gz tar.bz2 tar.xz tar.zst ps.gz maff ?q?',
    'video': 'mov mpeg mpg mpe mp4 m4v h264 h265 hevc avi mkv webm flv f4v wmv asf 3gp 3g2 mts m2ts ts vob ogv qt bik pss roq smk',
    'audio': 'mp3 wav wave aac m4a m4b m4p flac alac aiff aif aifc ogg oga opus wma caf mid midi amr au snd ac3 dts',
    # Ambiguous disk images, installed apps, keys, backups, VM and game data stay Others.
    'other': 'app bin iso img hdr bak bk pub fig dgn cel',
}


def extensions(cell):
    result = []
    for part in cell.lower().split('/'):
        part = part.strip().lstrip('.')
        match = re.fullmatch(r'([a-z]*)(\d+)-\.([a-z]*)(\d+)', part)
        if match and match[1] == match[3]:
            prefix, first, _, last = match.groups()
            result.extend(prefix + str(i).zfill(len(first)) for i in range(int(first), int(last) + 1))
        elif part:
            result.append(part)
    return result


def build_catalog():
    categories = {}
    for category, words in GROUPS.items():
        for ext in words.lower().split():
            categories[ext] = category
    # .ts is TypeScript by extension; a transport stream is ambiguous without content.
    categories['ts'] = 'code'
    categories['php?'] = 'code'
    for ext in ['jar', 'war', 'ear', 'mgz']:
        categories[ext] = 'archive'
    descriptions = {}
    with SOURCE.open(newline='') as source:
        for row in csv.DictReader(source):
            for ext in extensions(row['Extension']):
                descriptions.setdefault(ext, set()).add(row['Description'])
                categories.setdefault(ext, 'other')
    categories.update({'.ds_store': 'artifact', 'thumbs.db': 'artifact',
                       'desktop.ini': 'artifact', '.directory': 'artifact',
                       '._*': 'artifact', '~': 'artifact'})
    return categories, descriptions


def render():
    categories, descriptions = build_catalog()
    entries = []
    for ext, category in sorted(categories.items()):
        description = '; '.join(sorted(descriptions.get(ext, [])))
        # Only relevant, short reference text is sent to a classification request.
        description = ' '.join(description.split())[:160]
        entries.append(f'        {json.dumps(ext)}: Entry(category: .{category}, description: {json.dumps(description, ensure_ascii=False)}),')
    return '''// Generated by scripts/generate_extension_catalog.py. Do not edit the table by hand.
import Foundation

nonisolated struct ExtensionCatalog: Sendable {
    nonisolated struct Entry: Sendable {
        let category: FileType
        let description: String
    }

    static func category(for key: String) -> FileType? {
        entries[key.lowercased()]?.category
            ?? entries[key.lowercased().trimmingCharacters(in: CharacterSet(charactersIn: "."))]?.category
    }

    static func key(for name: String) -> String {
        let lower = name.lowercased()
        if [".ds_store", "thumbs.db", "desktop.ini", ".directory"].contains(lower) { return lower }
        if lower.hasPrefix("._") { return "._*" }
        if lower.hasSuffix("~") { return "~" }
        // Longest compound suffix wins, e.g. .nii.gz or .tar.gz.
        for suffix in compoundSuffixes where lower.hasSuffix("." + suffix) { return suffix }
        let ext = (lower as NSString).pathExtension
        if ext.range(of: "^php[0-9]$", options: .regularExpression) != nil { return "php?" }
        if ext.range(of: "^fc.$", options: .regularExpression) != nil { return "fc#" }
        if ext.range(of: "^.q.$", options: .regularExpression) != nil { return "?q?" }
        return ext
    }

    private static let compoundSuffixes = entries.keys.filter {
        $0.contains(".") && !$0.hasPrefix(".")
    }.sorted { $0.count == $1.count ? $0 < $1 : $0.count > $1.count }

    static let entries: [String: Entry] = [
''' + '\n'.join(entries) + '\n    ]\n}\n'


if __name__ == '__main__':
    DESTINATION.write_text(render())
    print(f'Generated {len(build_catalog()[0])} normalized extension/name rules.')
